name: Lint Python

on:
  pull_request:
    paths:
      - tracecat/**
      - .github/workflows/lint-python.yml

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get ruff version from requirements file
        id: version
        run: |
          VERSION=$(grep -m 1 -oP 'ruff==\K(.*)' requirements-lint.txt)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - uses: chartboost/ruff-action@v1
        with:
          src: tracecat/
          version: ${{ steps.version.outputs.version }}
          args: check --no-fix

      - uses: chartboost/ruff-action@v1
        with:
          src: tracecat/
          version: ${{ steps.version.outputs.version }}
          args: format --diff
